# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/rvfpga.xdc

# XDC: imports/src/liteDRAM.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_0 || ORIG_REF_NAME==BD_bidirec_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_0 || ORIG_REF_NAME==BD_bidirec_2_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_0 || ORIG_REF_NAME==BD_bidirec_3_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_0/BD_bidirec_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_4_0 || ORIG_REF_NAME==BD_bidirec_4_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_0/BD_bidirec_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_5_0 || ORIG_REF_NAME==BD_bidirec_5_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_0/BD_bidirec_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_6_0 || ORIG_REF_NAME==BD_bidirec_6_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_0/BD_bidirec_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_0 || ORIG_REF_NAME==BD_bidirec_7_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_8_0/BD_bidirec_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_8_0 || ORIG_REF_NAME==BD_bidirec_8_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_9_0/BD_bidirec_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_9_0 || ORIG_REF_NAME==BD_bidirec_9_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_10_0/BD_bidirec_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_10_0 || ORIG_REF_NAME==BD_bidirec_10_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_11_0/BD_bidirec_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_11_0 || ORIG_REF_NAME==BD_bidirec_11_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_12_0/BD_bidirec_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_12_0 || ORIG_REF_NAME==BD_bidirec_12_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_13_0/BD_bidirec_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_13_0 || ORIG_REF_NAME==BD_bidirec_13_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_14_0/BD_bidirec_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_14_0 || ORIG_REF_NAME==BD_bidirec_14_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_15_0/BD_bidirec_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_15_0 || ORIG_REF_NAME==BD_bidirec_15_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_16_0/BD_bidirec_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_16_0 || ORIG_REF_NAME==BD_bidirec_16_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_17_0/BD_bidirec_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_17_0 || ORIG_REF_NAME==BD_bidirec_17_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_18_0/BD_bidirec_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_18_0 || ORIG_REF_NAME==BD_bidirec_18_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_0/BD_bidirec_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_19_0 || ORIG_REF_NAME==BD_bidirec_19_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_20_0/BD_bidirec_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_20_0 || ORIG_REF_NAME==BD_bidirec_20_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_21_0/BD_bidirec_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_21_0 || ORIG_REF_NAME==BD_bidirec_21_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_22_0/BD_bidirec_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_22_0 || ORIG_REF_NAME==BD_bidirec_22_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_23_0/BD_bidirec_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_23_0 || ORIG_REF_NAME==BD_bidirec_23_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_24_0/BD_bidirec_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_24_0 || ORIG_REF_NAME==BD_bidirec_24_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_25_0/BD_bidirec_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_25_0 || ORIG_REF_NAME==BD_bidirec_25_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_26_0/BD_bidirec_26_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_26_0 || ORIG_REF_NAME==BD_bidirec_26_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_27_0/BD_bidirec_27_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_27_0 || ORIG_REF_NAME==BD_bidirec_27_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_28_0/BD_bidirec_28_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_28_0 || ORIG_REF_NAME==BD_bidirec_28_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_29_0/BD_bidirec_29_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_29_0 || ORIG_REF_NAME==BD_bidirec_29_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_30_0/BD_bidirec_30_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_30_0 || ORIG_REF_NAME==BD_bidirec_30_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_31_0/BD_bidirec_31_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_31_0 || ORIG_REF_NAME==BD_bidirec_31_0} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
