# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/rvfpga.xdc

# XDC: imports/src/liteDRAM.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_1 || ORIG_REF_NAME==BD_bidirec_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_2 || ORIG_REF_NAME==BD_bidirec_0_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_0 || ORIG_REF_NAME==BD_bidirec_2_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_1/BD_bidirec_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_1 || ORIG_REF_NAME==BD_bidirec_2_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_2/BD_bidirec_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_2 || ORIG_REF_NAME==BD_bidirec_2_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_3/BD_bidirec_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_3 || ORIG_REF_NAME==BD_bidirec_2_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_4/BD_bidirec_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_4 || ORIG_REF_NAME==BD_bidirec_2_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_5/BD_bidirec_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_5 || ORIG_REF_NAME==BD_bidirec_2_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_6/BD_bidirec_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_6 || ORIG_REF_NAME==BD_bidirec_2_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_7/BD_bidirec_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_7 || ORIG_REF_NAME==BD_bidirec_2_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_8/BD_bidirec_2_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_8 || ORIG_REF_NAME==BD_bidirec_2_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_9/BD_bidirec_2_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_9 || ORIG_REF_NAME==BD_bidirec_2_9} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_10/BD_bidirec_2_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_10 || ORIG_REF_NAME==BD_bidirec_2_10} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_11/BD_bidirec_2_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_11 || ORIG_REF_NAME==BD_bidirec_2_11} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_12/BD_bidirec_2_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_12 || ORIG_REF_NAME==BD_bidirec_2_12} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_13/BD_bidirec_2_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_13 || ORIG_REF_NAME==BD_bidirec_2_13} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_14/BD_bidirec_2_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_14 || ORIG_REF_NAME==BD_bidirec_2_14} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_15/BD_bidirec_2_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_15 || ORIG_REF_NAME==BD_bidirec_2_15} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_16/BD_bidirec_2_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_16 || ORIG_REF_NAME==BD_bidirec_2_16} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_18_0/BD_bidirec_18_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_18_0 || ORIG_REF_NAME==BD_bidirec_18_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_0/BD_bidirec_19_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_0 || ORIG_REF_NAME==BD_bidirec_19_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_1/BD_bidirec_19_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_1 || ORIG_REF_NAME==BD_bidirec_19_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_2/BD_bidirec_19_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_2 || ORIG_REF_NAME==BD_bidirec_19_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_3/BD_bidirec_19_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_3 || ORIG_REF_NAME==BD_bidirec_19_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_4/BD_bidirec_19_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_4 || ORIG_REF_NAME==BD_bidirec_19_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_5/BD_bidirec_19_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_5 || ORIG_REF_NAME==BD_bidirec_19_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_6/BD_bidirec_19_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_6 || ORIG_REF_NAME==BD_bidirec_19_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_7/BD_bidirec_19_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_7 || ORIG_REF_NAME==BD_bidirec_19_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_8/BD_bidirec_19_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_8 || ORIG_REF_NAME==BD_bidirec_19_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_9/BD_bidirec_19_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_9 || ORIG_REF_NAME==BD_bidirec_19_9} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_19_10/BD_bidirec_19_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_19_10 || ORIG_REF_NAME==BD_bidirec_19_10} -quiet] -quiet

# XDC: c:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.gen/sources_1/bd/BD/BD_ooc.xdc
