# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.runs/synth_1/rvfpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include}
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_params.vh}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh}}]
set_property is_global_include true [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh}}]
set_property is_global_include true [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh}}]
set_property is_global_include true [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh}}]
set_property is_global_include true [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_params.vh}}]
read_mem {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/sw/boot_main.mem}}
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/swerv_types.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/mem.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_cdc.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/binary_to_gray.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/bscan_tap.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cdc_fifo_gray.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/gray_to_binary.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/sync.sv}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/rvfpga.sv}
}
read_verilog -library xil_defaultlib {
  {c:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.gen/sources_1/bd/BD/hdl/BD_wrapper.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/OtherSources/clk_gen_nexys.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/litedram_core.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/litedram_top.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_alu.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_bufreg.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_csr.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_ctrl.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_decode.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_mem_if.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_if.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram_if.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_top.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_shift.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_state.v}
  {C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_top.v}
}
add_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/sources_1/bd/BD/BD.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.gen/sources_1/bd/BD/BD_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/constrs_1/imports/src/rvfpga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/constrs_1/imports/src/rvfpga.xdc}}]

read_xdc {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Usuario/Documents/Noveno Semestre/Arquitectura de computadores/RVfpgaSoC-v1.0/RVfpgaSoC/Labs/LabProjects/Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top rvfpga -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rvfpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rvfpga_utilization_synth.rpt -pb rvfpga_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
