# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1_v2019/Lab1_v2019.cache/wt [current_project]
set_property parent.project_path C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1_v2019/Lab1_v2019.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.2 [current_project]
set_property ip_output_repo c:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1_v2019/Lab1_v2019.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include
} [current_fileset]
read_verilog {
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_params.vh
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/global.h
}
set_property file_type "Verilog Header" [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh]
set_property is_global_include true [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh]
set_property file_type "Verilog Header" [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh]
set_property is_global_include true [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh]
set_property is_global_include true [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh]
set_property file_type "Verilog Header" [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh]
set_property is_global_include true [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh]
set_property file_type "Verilog Header" [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/global.h]
read_mem C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/sw/boot_main.mem
read_verilog -library xil_defaultlib -sv {
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_cdc.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/binary_to_gray.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/bscan_tap.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cdc_fifo_gray.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/include/swerv_types.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/gray_to_binary.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/SweRVolfSoC/SweRVEh1CoreComplex/mem.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/sync.sv
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/rvfpga.sv
}
read_verilog -library xil_defaultlib {
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.gen/sources_1/bd/BD/hdl/BD_wrapper.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/OtherSources/clk_gen_nexys.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/litedram_core.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/litedram_top.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_alu.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_bufreg.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_csr.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_ctrl.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_decode.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_mem_if.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_if.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram_if.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_top.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_shift.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_state.v
  C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/sources_1/imports/src/LiteDRAM/serv_1.0.2/rtl/serv_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/constrs_1/imports/src/rvfpga.xdc
set_property used_in_implementation false [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/constrs_1/imports/src/rvfpga.xdc]

read_xdc C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc
set_property used_in_implementation false [get_files C:/UIS/Arqui/RVfpga-SoC_Mantilla_Merchan/Lab1/Lab1.srcs/constrs_1/imports/src/liteDRAM.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rvfpga -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rvfpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rvfpga_utilization_synth.rpt -pb rvfpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
